package com.flf.entity;

import java.util.Date;

public class FmoUserAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmo_user_account.UID
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmo_user_account.JIFEN
     *
     * @mbggenerated
     */
    private Integer jifen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmo_user_account.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmo_user_account.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmo_user_account.GOLD
     *
     * @mbggenerated
     */
    private Integer gold;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmo_user_account.UID
     *
     * @return the value of fmo_user_account.UID
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmo_user_account.UID
     *
     * @param uid the value for fmo_user_account.UID
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmo_user_account.JIFEN
     *
     * @return the value of fmo_user_account.JIFEN
     *
     * @mbggenerated
     */
    public Integer getJifen() {
        return jifen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmo_user_account.JIFEN
     *
     * @param jifen the value for fmo_user_account.JIFEN
     *
     * @mbggenerated
     */
    public void setJifen(Integer jifen) {
        this.jifen = jifen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmo_user_account.CREATE_TIME
     *
     * @return the value of fmo_user_account.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmo_user_account.CREATE_TIME
     *
     * @param createTime the value for fmo_user_account.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmo_user_account.UPDATE_TIME
     *
     * @return the value of fmo_user_account.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmo_user_account.UPDATE_TIME
     *
     * @param updateTime the value for fmo_user_account.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmo_user_account.GOLD
     *
     * @return the value of fmo_user_account.GOLD
     *
     * @mbggenerated
     */
    public Integer getGold() {
        return gold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmo_user_account.GOLD
     *
     * @param gold the value for fmo_user_account.GOLD
     *
     * @mbggenerated
     */
    public void setGold(Integer gold) {
        this.gold = gold;
    }
}