package com.flf.dao;

import com.flf.entity.FmoUserAccount;
import com.flf.entity.FmoUserAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FmoUserAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmo_user_account
     *
     * @mbggenerated
     */
    int countByExample(FmoUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmo_user_account
     *
     * @mbggenerated
     */
    int deleteByExample(FmoUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmo_user_account
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmo_user_account
     *
     * @mbggenerated
     */
    int insert(FmoUserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmo_user_account
     *
     * @mbggenerated
     */
    int insertSelective(FmoUserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmo_user_account
     *
     * @mbggenerated
     */
    List<FmoUserAccount> selectByExample(FmoUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmo_user_account
     *
     * @mbggenerated
     */
    FmoUserAccount selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmo_user_account
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FmoUserAccount record, @Param("example") FmoUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmo_user_account
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FmoUserAccount record, @Param("example") FmoUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmo_user_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FmoUserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmo_user_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FmoUserAccount record);
}